version: '3.8'

services:
  astrbot:
    image: soulter/astrbot:latest
    container_name: astrbot
    ports: # mappings description: https://github.com/Soulter/AstrBot/issues/497
      - "6185:6185"
      - "6195:6195" # optional, wecom default port
      - "6199:6199" # optional, aiocqhttp default port
      - "6196:6196" # optional, qq official webhook default port
      - "11451:11451" # optional, gewechat default port
    volumes:
      - ./data:/AstrBot/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
